### ISSUE TITLE
Calculating wrong number of participants and total income

### ISSUE THREAD

**Issue by pontushagman-zz** [BVNetwork/Attend#1]
Under the invoicing tab. The calculation for number of participants and total income is not correct.
https://www.dropbox.com/s/bs8j9zvypda8sy6/2016-02-02_090304.jpg?dl=0

**Comment by evest** [comment]
Github supports pasting images into the editor :-)

![image](https://cloud.githubusercontent.com/assets/6423464/12743718/dfd40362-c98f-11e5-81e2-4a56690c8375.png)

**Comment by pontushagman-zz** [comment]
Fancy :)

**Comment by laerum** [comment]
Fixed!
