### ISSUE TITLE
Edit participant info fails

### ISSUE THREAD

**Issue by laerum** [BVNetwork/Attend#16]
Steps to reproduce:
1. Edit participant
2. Edit form
3. Change some data
4. Save form

Error message
System.Web.HttpUnhandledException: Content with id '25973' is of type 'Castle.Proxies.ParticipantBlockProxy' which does not inherit required type 'EPiServer.Core.PageData'

/modules/bvnetwork.attend/views/blocks/participantblockpreview.aspx

**Comment by pontushagman-zz** [comment]
Full stack trace =>
![image](https://cloud.githubusercontent.com/assets/3648033/20215384/1a88f66c-a814-11e6-8451-e22895fbb9ac.png)
