### ISSUE TITLE
Could not load type 'EPiServer.Core.NullLanguageSelector' 

### ISSUE THREAD

**Issue by anjumrizwi** [BVNetwork/Attend#29]
I am facing this issue after creating event page. Page creation success but when I try to load throw exception
 
Could not load type 'EPiServer.Core.NullLanguageSelector' from assembly 'EPiServer, Version=10.0.1.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'

I have installed QuickSilver from GitHub. Below is my config for reference

 <package id="EPiServer.CMS" version="10.0.1" targetFramework="net452" />
  <package id="EPiServer.CMS.Core" version="10.0.1" targetFramework="net452" />
  <package id="EPiServer.CMS.UI" version="10.0.2" targetFramework="net452" />
  <package id="EPiServer.CMS.UI.Core" version="10.0.2" targetFramework="net452" />
  <package id="EPiServer.Framework" version="10.0.1" targetFramework="net452" />
  <package id="EPiServer.Logging.Log4Net" version="2.1.0" targetFramework="net452" />
  <package id="EPiServer.Packaging" version="3.3.0" targetFramework="net452" />
  <package id="EPiServer.Packaging.UI" version="3.3.0" targetFramework="net452" />

**Comment by laerum** [comment]
This is because Attend is compatible with Episerver 9.x. A 10.x version will be available soon.
