### ISSUE TITLE
CMS10 compatability.

### ISSUE THREAD

**Issue by jorgenhelgheim** [BVNetwork/Attend#31]
I can see that the current version does not support CMS 10. Ref commit: https://github.com/BVNetwork/Attend/commit/a6bf7fdc0647201a74d84cdf4bd1ea362546c93f

Have BVNetwork any plans for upgrading this module? Does it involve a big change for this module?

cc @evest

**Comment by pontushagman-zz** [comment]
BV Network has a plan to upgrade Attend in July. The work is done on behalf of a Episerver customer requesting CMS 10 support. The focus will be to add this support with minimal changes to the module.

**Comment by imawomble** [comment]
Hi - is this update still planned?

**Comment by pontushagman-zz** [comment]
Yes, please test the updated version here: https://github.com/BVNetwork/Attend/pull/32

**Comment by imawomble** [comment]
Great, thank you

**Comment by pontushagman-zz** [comment]
Attend is now upgraded to support Episerver 10. Available on nuget.episerver.com
