### ISSUE TITLE
Attend is not using system language

### ISSUE THREAD

**Issue by ninamoberg** [BVNetwork/Attend#36]
If the user has selected "System language" as his language in "My settings"/"Display options" Attend is not able to show system language. All text in Attend is shown as: [Missing text '/attend/edit/participants' for 'Invariant Language(Invariant Country)']
This stopped working in the EPI10 version of Attend

**Comment by pontushagman-zz** [comment]
I have problem to recreate this problem on a standard Alloy Site with Attend v.10.0.3 installed. Could you please check what setting you have for fallbackCulture ?

![image](https://user-images.githubusercontent.com/3648033/30800841-a42e460c-a1e1-11e7-879f-d95ba3df54e0.png)

**Comment by ninamoberg** [comment]
It is set to "nn-NO"

**Comment by pontushagman-zz** [comment]
Attend is not translated to “Norwegian, Nynorsk” (nn-NO). To solve this you could:
1. Translate the language files to "nynorsk" for Attend and we would add it to the Attend module
or
2. Change fallbackCulture to "no" or "en"

![image](https://user-images.githubusercontent.com/3648033/30805384-69695b1e-a1f1-11e7-9f51-3054e32b6db7.png)

**Comment by ninamoberg** [comment]
We have already made copies of the norwegian lanuage files for Attend and added them as nn-NO. This did not help. We can try to change fallback language to no.

**Comment by pontushagman-zz** [comment]
That should work. Add a file to your project like this:

![image](https://user-images.githubusercontent.com/3648033/30806472-201c66e0-a1f6-11e7-98e8-0e78a00fbfab.png)

With content:
`<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<languages>
  <language name="Norwegian nynorsk" id="nn-NO">
    <attend>
      <admin>
        <import>Import</import>
...`

If you DO translate it. We could add it to the module :)

**Comment by ninamoberg** [comment]
Looks like setting the fallback language to "no" fixed the problem :)
