### ISSUE TITLE
Attend.Forms does not work with subclass of FormContainerBlock

### ISSUE THREAD

**Issue by Arthyon** [BVNetwork/Attend#41]
Background:
Our project uses a custom form container block inheriting from `EPiServer.Forms.Implementation.Elements.FormContainerBlock` because we need to add some properties to all created forms. To prevent the editors from creating the wrong block we have hidden the regular FormContainerBlock from edit mode.

Attend's Form-implementation uses a block controller (`AttendformContainerBlockController`) to set required properties, such as RedirectToPage (used to identify the correct event when posting the form). This block controller will only work for the specific ModelType `FormContainerBlock` as the TemplateDescriptor-parameter Inherit is set to False.

We can work around this by defining a block controller inheriting `AttendFormContainerBlockController` and making the TemplateDescriptor's ModelType match our custom form block. This is **not** an obvious workaround, and we used quite a lot of time figuring out why no participants were registered.

To make this work out of the box for others in our situation, setting `Inherit = True` on the TemplateDescriptor will work fine. If this is a use case that should be solved by the consumer of Attend, which is fair enough, it would be great if it was added to the wiki.

**Comment by pontushagman-zz** [comment]
Thanks for you for feedback!

Your suggestion is to add `Inherit = True`  on `AttendFormContainerBlockController`, right?
Do you want to make the change (with a pull request)?

**Comment by Arthyon** [comment]
That's correct. I opened a PR ( #42 ) for it now. 
I have tested this on an Alloy site using both a custom form inheriting from FormContainerBlock and the original FormContainerBlock from the Episerver.Forms-package. Both work great now, so this shouldn't break existing functionality.

**Comment by pontushagman-zz** [comment]
Great stuff. Thanks for contributing!
