### ISSUE TITLE
Event form is not displayed when dragged into ContentArea

### ISSUE THREAD

**Issue by jrmathletics** [BVNetwork/Attend#5]
After following the installation guide (installing the nuget package) and creating an event successfully I am now trying to add it to a contentarea. When doing so I'm met with the following error message: "The 'EventPage' can not be displayed." My assumption is that the correct controller/partialview is not found for the event. Any clue to why this is the case?

I'm working in a fresh Alloy demo site.

**Comment by laerum** [comment]
I tried to install the module on a fresh Alloy site today. I did get an issue with the Razor version being referenced. I have created a new nuget targeting version 3.0.0. The form is now being displayed correctly. The new version (5.2.23) will be available in the nuget feed in a few hours. Hope this helps. 

![image](https://cloud.githubusercontent.com/assets/10400951/13032133/88eb29ca-d2e7-11e5-8b8e-0589c263d46e.png)

**Comment by laerum** [comment]
Did not hear back - considered fixed.
